//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _050_CrudImagenes.Modelos.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaRu
    {
        public int IdPersona { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<System.DateTime> FechaNaci { get; set; }
        public Nullable<int> Edad { get; set; }
        public string FotoRut { get; set; }
        public string NombreFoto { get; set; }
    }
}
